### PR TITLE
included dev setup docs

### PR DESCRIPTION
**Pull request by harshad16**
included dev setup docs
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/open-services-group/peribolos-as-a-service/issues/22

### CODE REVIEW

**Comment by tumido** [comment]
/cc @SamoKopecky @mimotej 

please review

**Comment by mimotej** [comment]
Looks great! Just one thing I am thinking that this section is not necessary since you are describing setup process below... https://github.com/open-services-group/peribolos-as-a-service/blob/073643591d0ea51cd1577c537ba9f6ac0bbb7391/README.md#run-directly-using-npm
Otherwise LGTM

**Comment by harshad16** [comment]
> Looks great! Just one thing I am thinking that this section is not necessary since you are describing setup process below... https://github.com/open-services-group/peribolos-as-a-service/blob/073643591d0ea51cd1577c537ba9f6ac0bbb7391/README.md#run-directly-using-npm Otherwise LGTM

no preference on my side, if the team feels like removing that bit, let me know
happy to remove it from this pr.

**Comment by SamoKopecky** [comment]
Like it a lot!
I just wonder if we maybe should create a `podman-compose.yaml` or `docker-compose.yaml` since I think its now supported by `podman`. Personally when I was testing the app it made a lot more sense to just run the compose file instead of one long `podman run`. It might also help if decide to add more env variables to `.env`, since we can just pass the env variables straight from `.env` to the compose file.
But maybe thats just my preference. Otherwise LGTM.

**Comment by tumido** [comment]
> Like it a lot! I just wonder if maybe we should create a `podman-compose.yaml` or `docker-compose.yaml` since I think its now supported by `podman`. Personally when I was testing the app it made a lot more sense to just run the compose file instead of one long `podman run`. It might also help if we decide to add more env variables to `.env`, since we can just pass the env variables straight from the `.env` file to the compose file. But maybe thats just my preference. Otherwise LGTM.

I don't think podman is used in dev setup anyways. In dev you do `npm start` to run it locally and you're all set. And if you build it into a container, then you probably use it in OCP anyways, and we have a dev overlay for that. I don't think we need the podman mentioned here at all in the end.

**Comment by harshad16** [comment]
> I don't think podman is used in dev setup anyways. In dev you do `npm start` to run it locally and you're all set. And if you build it into a container, then you probably use it in OCP anyways, and we have a dev overlay for that. I don't think we need the podman mentioned here at all in the end.

I think we can remove the podman , once we have the s2i changes in, as it would require a different command to run as a container.

**Comment by harshad16** [comment]
Is there any changes to be done?
is this missing something for not being merged ?

**Review by tumido — APPROVED** [review]
@harshad16 I don't have any change requests. I like it as it is :slightly_smiling_face: 

/lgtm
/approve

**Pull request merged**
